get:
    tags:
        - details
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        Full details of a book:
                            value: >-
                                {id: 3, title:"The Bear and The Nightingale", author: "Katherine Arden", year:
                                2017, pages: 3014}
            description: Returns full details of a given id book
        '404':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/error'
                    examples:
                        Game /w+ was not found:
                            value: Game \\w+ was not found in game array.
            description: Book was not found in books array
    operationId: id
    description: Returns full details of a given id book
delete:
    tags:
        - delete-book
    responses:
        '204':
            description: Book successfully deleted.
        '404':
            description: Book to delete not found.
    summary: Book to be deleted
    description: Deletes book of given id
parameters:
    -
        examples:
            Id:
                value: '35'
        name: id
        description: Unique book identifier
        schema:
            type: string
        in: path
        required: true
